# Generated by Django 2.0.3 on 2019-11-08 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antenna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AntennaState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('antenna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icd.Antenna')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ObsID', models.IntegerField()),
                ('StartTime', models.DateTimeField()),
                ('StopTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataPointName', models.CharField(max_length=50)),
                ('Value', models.FloatField()),
                ('Unit', models.CharField(max_length=5)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('ReceiverBitmap', models.CharField(max_length=100)),
                ('HBABitmap', models.CharField(max_length=100)),
                ('LBABitmap', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StationObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReceiverBitmap', models.CharField(max_length=100)),
                ('HBABitmap', models.CharField(max_length=100)),
                ('LBABitmap', models.CharField(max_length=100)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icd.Observation')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='icd.Station')),
            ],
        ),
        migrations.AddField(
            model_name='sensordata',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icd.Station'),
        ),
        migrations.AddField(
            model_name='observation',
            name='stations',
            field=models.ManyToManyField(to='icd.Station'),
        ),
        migrations.AddField(
            model_name='antenna',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icd.Station'),
        ),
    ]
